# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tburlacu <tburlacu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/31 10:51:35 by tburlacu          #+#    #+#              #
#    Updated: 2022/11/03 16:05:51 by tburlacu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS			=	ft_isalnum.c ft_isprint.c ft_memcmp.c ft_strdup.c ft_putendl_fd.c\
					ft_strlcat.c ft_strncmp.c ft_atoi.c ft_isalpha.c ft_strtrim.c ft_putnbr_fd.c\
					ft_memcpy.c ft_strchr.c ft_strlcpy.c ft_substr.c ft_strjoin.c\
					ft_strnstr.c ft_tolower.c ft_bzero.c ft_isascii.c ft_memcpy.c\
					ft_memmove.c ft_strlen.c ft_strrchr.c ft_calloc.c ft_putchar_fd.c\
					ft_toupper.c ft_isdigit.c ft_memchr.c ft_memset.c ft_putstr_fd.c\
					
OBJS			= $(SRCS:.c=.o)

NAME			= libft.a
CC				= gcc
RM				= rm -f
CFLAGS			= -Wall -Wextra -Werror -I.

all:			$(NAME)

$(NAME):		$(OBJS)
				ar rcs $(NAME) $(OBJS)

clean:
				$(RM) $(OBJS)

fclean:			clean
				$(RM) $(NAME)

re:				fclean $(NAME)

.PHONY:			all clean fclean re bonus